# Generated by Django 3.0.6 on 2020-05-06 14:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('url', models.CharField(max_length=12, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='FloorsHome',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('floor', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Furniture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Level',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='NumberRooms',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='RealEstate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=70, verbose_name='Tytuł')),
                ('price', models.FloatField(verbose_name='Cena')),
                ('area', models.FloatField()),
                ('description', models.TextField(verbose_name='Opis')),
                ('photos', models.ImageField(blank=True, upload_to='', verbose_name='Dodaj zdjęcia')),
                ('location', models.CharField(max_length=50, verbose_name='Lokalizacja')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base_app.Category', verbose_name='Kategoria')),
            ],
        ),
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='TypeOfferts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='TypeOffice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='TypePlot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Garage',
            fields=[
                ('realestate_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='base_app.RealEstate')),
            ],
            bases=('base_app.realestate',),
        ),
        migrations.CreateModel(
            name='Magazine',
            fields=[
                ('realestate_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='base_app.RealEstate')),
            ],
            bases=('base_app.realestate',),
        ),
        migrations.CreateModel(
            name='Other',
            fields=[
                ('realestate_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='base_app.RealEstate')),
            ],
            bases=('base_app.realestate',),
        ),
        migrations.AddField(
            model_name='realestate',
            name='type_offerts',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base_app.TypeOfferts'),
        ),
        migrations.CreateModel(
            name='Plot',
            fields=[
                ('realestate_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='base_app.RealEstate')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base_app.TypePlot')),
            ],
            bases=('base_app.realestate',),
        ),
        migrations.CreateModel(
            name='Office',
            fields=[
                ('realestate_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='base_app.RealEstate')),
                ('level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base_app.Level', verbose_name='Poziom')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base_app.TypePlot', verbose_name='Typ')),
            ],
            bases=('base_app.realestate',),
        ),
        migrations.CreateModel(
            name='Home',
            fields=[
                ('realestate_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='base_app.RealEstate')),
                ('parcel_area', models.FloatField()),
                ('floor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base_app.FloorsHome')),
                ('furniture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base_app.Furniture')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base_app.Type')),
            ],
            bases=('base_app.realestate',),
        ),
        migrations.CreateModel(
            name='Apartament',
            fields=[
                ('realestate_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='base_app.RealEstate')),
                ('furniture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base_app.Furniture', verbose_name='Umeblowanie')),
                ('level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base_app.Level', verbose_name='Poziom')),
                ('number_room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base_app.NumberRooms', verbose_name='Liczba pokoi')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base_app.Type', verbose_name='Rodzaj zabudowy')),
            ],
            bases=('base_app.realestate',),
        ),
    ]
