# Generated by Django 3.0.6 on 2020-05-06 19:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='home',
            name='floor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base_app.FloorsHome', verbose_name='Liczna pięter'),
        ),
        migrations.AlterField(
            model_name='home',
            name='furniture',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base_app.Furniture', verbose_name='Umeblowanie'),
        ),
        migrations.AlterField(
            model_name='home',
            name='parcel_area',
            field=models.FloatField(verbose_name='Powierzchnia działki'),
        ),
        migrations.AlterField(
            model_name='home',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base_app.Type', verbose_name='Rodzaj zabudowy'),
        ),
        migrations.AlterField(
            model_name='office',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base_app.TypePlot', verbose_name='Przeznaczenie lokalu'),
        ),
        migrations.AlterField(
            model_name='plot',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base_app.TypePlot', verbose_name='Rodzaj'),
        ),
        migrations.AlterField(
            model_name='realestate',
            name='area',
            field=models.FloatField(verbose_name='Powierzchnia'),
        ),
        migrations.AlterField(
            model_name='realestate',
            name='photos',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='Dodaj zdjęcia'),
        ),
        migrations.AlterField(
            model_name='realestate',
            name='type_offerts',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base_app.TypeOfferts', verbose_name='Rodzaj oferty'),
        ),
    ]
