# Generated by Django 3.0.6 on 2020-05-07 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base_app', '0002_auto_20200506_1910'),
    ]

    operations = [
        migrations.AddField(
            model_name='realestate',
            name='create_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
